<?php

$squareType = $this->option('subject.square.type');

if ($this->notBookableReason) {
    $reason = $this->notBookableReason;
} else {
    $reason = $this->t('This %s is already occupied.');
}

echo sprintf('<p><span class="red">' . $reason . '</span></p>', $squareType);

foreach ($this->reservations as $rid => $reservation):
    echo"<p>";
        echo "<b>" . $this->timeRange($reservation->get('time_start'), $reservation->get('time_end'), '%s to %s') . "</b>";
        echo " " . $this->t('from') . " " . $reservation->getExtra('booking')->getExtra('user')->get('alias');
    echo "</p>";
endforeach;