<?php

$squareType = $this->option('subject.square.type');

foreach ($this->bookingsFromUser as $bid => $booking) {
    echo sprintf('<p><span class="green">' . $this->t('This %s has been %sbooked to you%s.') . '</span></p>',
        $squareType, '<b>', '</b>');

    if ($this->validator->isCancellable($booking)) {
        echo sprintf('<p><a href="%s" class="default-button squarebox-internal-link"><span class="symbolic symbolic-cross">%s</span></a></p>',
            $this->url('square/booking/cancellation', [], ['query' => ['bid' => $bid]]), $this->t('Cancel this booking'));
    } else {
        echo '<p><em>' . $this->t('This booking cannot be cancelled anymore online.') . '</em></p>';
    }
}

if ($this->bookable) {
    echo sprintf('<p><span class="green">' . $this->t('This %s is still free.') . '</span></p>', $squareType);

    $url = $this->url('square', [], ['query' => [
        'ds' => $this->dateStart->format('Y-m-d'),
        'de' => $this->dateEnd->format('Y-m-d'),
        'ts' => $this->dateStart->format('H:i'),
        'te' => $this->dateEnd->format('H:i'),
        's' => $this->square->need('sid'),
        'f' => 'fb']]);
}

    foreach ($this->reservations as $rid => $reservation):
        echo"<p>";
            echo "<b>" . $this->timeRange($reservation->get('time_start'), $reservation->get('time_end'), '%s to %s') . "</b>";
            echo " " . $this->t('from') . " " . $reservation->getExtra('booking')->getExtra('user')->get('alias');
        echo "</p>";
    endforeach;

if ($this->bookable) {
    foreach ($this->reservations as $rid => $reservation):
        echo"<p>";
            echo "<b>" . $this->timeRange($reservation->get('time_start'), $reservation->get('time_end'), '%s to %s') . "</b>";
            echo " " . $this->t('from') . " " . $reservation->getExtra('booking')->getExtra('user')->get('alias');

            $booking = $reservation->getExtra('booking');
            $playerNames = $booking->getMeta('player-names');
            $playerNameNotes = '';
            if ($playerNames) {
                $playerNamesUnserialized = @unserialize($booking->getMeta('player-names'));
                if ($playerNamesUnserialized && is_array($playerNamesUnserialized)) {
                    foreach ($playerNamesUnserialized as $i => $playerName) {
                        $playerNameNotes .= ' & ' . $playerName['value'];
                    }
                }
            }
            echo $playerNameNotes;

            if ($booking->getMeta('teacher') == 1) {
                echo " " . $this->t('(with teacher)');
            }
       echo "</p>";
    endforeach;

    foreach ($this->reservations as $rid => $reservation):
        echo"<p>";
            echo "<b>" . $this->timeRange($reservation->get('time_start'), $reservation->get('time_end'), '%s to %s') . "</b>";
            echo " " . $this->t('from') . " " . $reservation->getExtra('booking')->getExtra('user')->get('alias');
            if ($reservation->getExtra('booking')->getMeta('constructions') == 1) {
                echo " " . "(mit Aufbauten)";
            }
        echo "</p>";
    endforeach;

    echo sprintf('<p><a href="%s" class="default-button squarebox-internal-link"><span class="symbolic symbolic-plus">%s</span></a></p>',
        $url, $this->t('Book more'));
}